### ISSUE TITLE
Unable to load library gmp

### ISSUE THREAD

**Issue by videlec** [flatsurf/gmpxxyy#2]
Installing went fine but I have trouble loading
```
$ sage-dev -python3
Python 3.7.3 (default, Feb  5 2020, 13:05:12) 
[GCC 9.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gmpxxyy
Error in <TUnixSystem::FindDynamicLibrary>: gmp[.so | .dll | .dylib | .sl | .dl | .a] does not exist in .:/opt/sage/local/lib/python3.7/site-packages/cppyy_backend/lib::/opt/sage/local/lib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/sage/local/lib/python3.7/site-packages/gmpxxyy/__init__.py", line 31, in <module>
    from .cppyy_gmpxx import mpz, mpq, mpf
  File "/opt/sage/local/lib/python3.7/site-packages/gmpxxyy/cppyy_gmpxx.py", line 134, in <module>
    cppyy.load_library("gmp")
  File "/opt/sage/local/lib/python3.7/site-packages/cppyy/__init__.py", line 149, in load_library
    raise RuntimeError("Unable to load library "+name)
RuntimeError: Unable to load library gmp
```

**Comment by saraedum** [comment]
There's no `gmp.so` in /opt/sage/local/lib? Hm…guess you are using your local gmp.so and did not build  the one that comes with Sage?

**Comment by videlec** [comment]
Indeed
```
$ ls /opt/sage/local/lib | grep gmp
libcddgmp.a
libcddgmp.so
libcddgmp.so.0
libcddgmp.so.0.0.0
libpari-gmp.so.2.11.2
libpari-gmp.so.6
```

**Comment by saraedum** [comment]
Can you try to run
```
import cppyy
cppyy.add_library_path('/usr/lib')
import gmpxxyy
```

It's not really a solution in general but does this work?

**Comment by saraedum** [comment]
I can reproduce the issue in the SageMath docker image.

**Comment by saraedum** [comment]
This is now https://bitbucket.org/wlav/cppyy/issues/203/library-search-path-very-short-without.

As a quick workaround you should be able to `LD_LIBRARY_PATH=NonEmptyString sage`

**Comment by saraedum** [comment]
This has been fixed in cppyy upstream. Can you check that it works now?

**Comment by saraedum** [comment]
This seems to work for you by now.
